# Generated by Django 2.0.5 on 2018-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCort', '0002_auto_20180506_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
            ],
        ),
    ]
