# Generated by Django 2.0.5 on 2018-05-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCort', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='username',
        ),
        migrations.AddField(
            model_name='reservation',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myCort.Users'),
            preserve_default=False,
        ),
    ]
